# Generated by Django 3.2.4 on 2021-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('facebook', models.URLField(max_length=60)),
                ('twitter', models.URLField(max_length=60)),
                ('google_plus', models.URLField(max_length=60)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
