# Generated by Django 3.2.4 on 2021-06-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210612_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_itle',
            new_name='car_title',
        ),
    ]
