# Generated by Django 3.2.4 on 2021-06-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_car_itle_car_car_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='feul_type',
            new_name='fuel_type',
        ),
    ]
